socket:
  host: 0.0.0.0
  port: 9092

server:
  port: 8877

spring:
  devtools: true
  data:
    mongodb:
      authentication-database: admin
      username: capstone
      password: capstonevlu
      database: capstone
      port: 50370
      host: 35.240.226.176
      auto-index-creation: true
